name: Update Rebrickable Sets Data

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0   # ensures we get full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run download script
        run: python scripts/download_sets.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ðŸ§± Update Rebrickable sets data [automated]"
          commit_author: "GitHub Actions <actions@github.com>"
          file_pattern: |
            data/sets.json
            data/sets.txt
            data/minifigs.json
            data/minifigs.txt
            data/img_url_cache.json
